### ISSUE TITLE
Make it an app that any teacher can use to make a currency and even upgrade it to a full classroom economy?

### ISSUE THREAD

**Issue by Papaya-Voldemort** [skbidisigma1/MoBank#2]
Make it an app that any teacher can use to make a currency and even upgrade it to a full classroom economy?

**Comment by Papaya-Voldemort** [comment]
Wow I just saw the new features and they are amazing although it sent me a email verification message and before that on the site told me sign in failed...

**Comment by skbidisigma1** [comment]
Yeah it's not quite fully functional... I'll explain later all the stuff that got in the way as well it was awful. I'll try to fix now

**Comment by skbidisigma1** [comment]
Also it registered you 5 times... did you sign up 5 times or is that a bug? Either way I'll have to add limits on that

**Comment by Papaya-Voldemort** [comment]
Yea I kept pressing the button since nothing was happening until it did, and then I got like 50 messages :)
